esphome:
  name: hanzi-frame
  friendly_name: HanziFrame
  build_flags:
    - "-mfix-esp32-psram-cache-issue"

external_components:
  - source:
      type: local
      path: custom_components
    components: [t547]

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  flash_mode: qio
  flash_frequency: 80MHz
  cpu_frequency: 240MHz
  toolchain: esp-idf
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

# HTTP Request component (required for online_image)
http_request:
  useragent: "HanziFrame"
  timeout: 10s
  verify_ssl: false

# Online image with Chinese words
image:
  - platform: online_image
    url: "http://homeassistant.local:8123/local/word.png" # You can change homeassistant.local to your HA Server IP address
    format: PNG
    id: chinese_word_image
    type: GRAYSCALE  # Grayscale is suitable for an E-Ink display
    resize: 960x540   # Exactly the size of the display
    update_interval: never  # Update only on request
    on_download_finished:
      - logger.log: "Image downloaded successfully"
      - component.update: epaper_display
    on_error:
      - logger.log: "Error downloading image"

# Virtual button to refresh the screen
button:
  - platform: template
    name: "Refresh Chinese word"
    id: refresh_chinese_word
    on_press:
      - logger.log: "Request to refresh Chinese word"
      - component.update: chinese_word_image

# Display configuration
display:
  - platform: t547
    id: epaper_display
    rotation: 0
    update_interval: never  # Update only when a new image is received
    lambda: |-
      // Clear the screen
      it.fill(COLOR_OFF);

      // Display the Chinese word (image takes up the whole screen)
      it.image(0, 0, id(chinese_word_image));
